name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - python=3.8.16
  - numpy=1.23.4
  - mlflow=1.14.1
  - pandas=1.2.3
  - pytest=6.2.2
  - scipy=1.6.1
  - pip:
      - wandb==0.10.21